### ISSUE TITLE
vc4-fkms-3d on versions >= 4.19.56.20190702

### ISSUE THREAD

**Issue by lifof** [sakaki-/bcmrpi3-kernel#9]
Hello there

I don't know if it's just me or everyone using this awesome kernel, but since I updated to version 4.19.56.20190702 I can't use this in /boot/config.txt cause it's causing a crash on boot :
`dtoverlay=vc4-fkms-v3d`

by the way I'm on Archlinuxarm on Raspberry pi 3B

Thanks in advance

**Comment by sakaki-** [comment]
Hi lifof, 

Sorry to hear you have been experiencing problems with this ><

Unfortunately yes, there have been issues with the vc4 and v4l2 drivers recently (upstream) on 64-bit due to changes introduced for the new Pi4 launch. Hopefully will be resolved shortly. Please mask / hold back / pin the kernel version as workaround in the meantime. 

Best, sakaki 
-- 
sakaki@deciban.com

**Comment by lifof** [comment]
Hello sakaki,

No need to be sorry, it's not causing me any problems, so I'll stick with version 4.19.50.20190618 cause it's the last one that has vc4 working for me.

Thank you for your prompt response

**Comment by sakaki-** [comment]
Think vc4 may be working again now - it certainly is on the Pi4 kernels. Please try again with the latest release and see how things go.
Best, sakaki

**Comment by lifof** [comment]
No still the same behavior on version 4.19.59.20190724

Thanks anyway :)

**Comment by lifof** [comment]
Hello just got back from vacations here and wanted to share the latest news about this issue.
Great news Its fixed 😄 just tested it on version 4.19.69.20190903 and it's working.

Thanks @sakaki- for the weekly updates

**Comment by sakaki-** [comment]
Glad to hear it is working for you now!
Best, sakaki
